### ISSUE TITLE
关于订阅里的clash问题

### ISSUE THREAD

**Issue by wsa01378** [v2board/v2board#365]
```
experimental:
    ignore-resolve-fail: true
dns:
    enable: true
    ipv6: false
    enhanced-mode: redir-host
    nameserver: [1.2.4.8, 223.5.5.5]
    fallback: ['tls://1.0.0.1:853', 'tls://dns.google:853']
```

这段你要不要考虑改进下。因为我删了这段，真延迟测试结果准确多了。之前经常假timeout
