### ISSUE TITLE
[BUG] Clash配置文件自定义，proxies进行限制后无效

### ISSUE THREAD

**Issue by AlexANSO** [v2board/v2board#675]
Clash配置文件自定义，proxies进行限制后无效，还是会将全部节点显示出来
我是这么进行配置的，比如我使用proxies字段添加ssr1-2但是更新后还是会出现其他的节点

```
proxy-groups:
  - name: ⚖️ 负载均衡-轮询
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: round-robin
    proxies:
      - ss1
      - ss2
```

以解决
需要修改为
```
proxy-groups:
  - name: ⚖️ 负载均衡-轮询
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: round-robin
    proxies:
      - /ss1/
      - /ss2/
```
